FREEZE_LAST_LAYER_EPOCHS: 1
GRADIENT_CLIPPING: 3.0
LOSS:
  IS_AVERAGE: true
  NAME: dinov2
LR_SCHEDULER:
  FINAL_VALUE: 1.0e-06
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  LEARNING_RATE: 4.0e-03
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 10
  WARMUP_VALUE: 0
NET:
  DEPTH: 12
  DINO:
    CENTERING: centering
    HEAD_BOTTLENECK_DIM: 256
    HEAD_HIDDEN_DIM: 2048
    HEAD_OUT_DIM: 65536
    IS_BN_IN_HEAD: false
    IS_NORM_LAST_LAYER: true
    NUM_HEAD_LAYERS: 3
  DROP_PATH_RATE: 0.3
  DROP_RATE: 0.0
  EMBED_DIM: 768
  IN_CHANS: 3
  MLP_RATIO: 4.0
  NAME: dinov2
  NUM_HEADS: 12
  PATCH_SIZE: 16
NUM_EPOCHS: 200
OPTIMIZER:
  BETAS:
  - 0.9
  - 0.999
  MOMENTUM: 0.9
  NAME: adamw
TM_SCHEDULER:
  FINAL_VALUE: 1.0
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  TEACHER_MOMENTUM: 0.992
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 0.0
TT_SCHEDULER:
  FINAL_VALUE: 0.07
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  TEACHER_TEMP: 0.07
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 30
  WARMUP_VALUE: 0.04
WD_SCHEDULER:
  FINAL_VALUE: 0.4
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 0.0
  WEIGHT_DECAY: 0.04
