AUG:
  GLOBAL_CROP_SIZE: 512
  GLOBAL_SCALE:
  - 0.2
  - 1.0
  IS_AUG: true
GRADIENT_CLIPPING: None
LOSS:
  NAME: mae
LR_SCHEDULER:
  FINAL_VALUE: 1.0e-06
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  LEARNING_RATE: 1.0e-03
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 20
  WARMUP_VALUE: 0
NET:
  DEPTH: 12
  EMBED_DIM: 768
  IN_CHANS: 3
  MLP_RATIO: 4.0
  NAME: mae
  NUM_HEADS: 12
  PATCH_SIZE: 16
NUM_EPOCHS: 200
OPTIMIZER:
  BETAS:
  - 0.9
  - 0.95
  NAME: adamw
WD_SCHEDULER:
  FINAL_VALUE: 0.05
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 0.0
  WEIGHT_DECAY: 0.05
