AUG:
  CONTRAST: 0.4
  GLOBAL_CROP_SIZE: 512
  GLOBAL_SCALE:
  - 0.08
  - 1.0
  HUE: 0.1
  INTENSITY: 0.4
  IS_AUG: true
  NUM_GLOBAL: 2
  NUM_LOCAL: 0
  SATURATION: 0.2
GRADIENT_CLIPPING: None
LOSS:
  NAME: mocov3
LR_SCHEDULER:
  FINAL_VALUE: 1.0e-06
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  LEARNING_RATE: 1.0e-03
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 10
  WARMUP_VALUE: 0
NET:
  DEPTH: 12
  MOCO:
    HEAD_OUT_DIM: 256
    HEAD_HIDDEN_DIM: 4096
  DROP_PATH_RATE: 0.0
  DROP_RATE: 0.0
  EMBED_DIM: 768
  IN_CHANS: 3
  MLP_RATIO: 4.0
  NAME: mocov3
  NUM_HEADS: 12
  PATCH_SIZE: 16
NUM_EPOCHS: 200
OPTIMIZER:
  MOMENTUM: 0.9
  NAME: lars
TM_SCHEDULER:
  FINAL_VALUE: 1.0
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  TEACHER_MOMENTUM: 0.99
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 0.0
TT_SCHEDULER:
  FINAL_VALUE: 1.0
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  TEACHER_TEMP: 1.0
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 1.0
WD_SCHEDULER:
  FINAL_VALUE: 1e-6
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 0.0
  WEIGHT_DECAY: 1e-6
