AUG:
  CONTRAST: 0.4
  CROP_RATIO:
  - 0.75
  - 1.33
  CROP_SCALE:
  - 0.4
  - 1.0
  GLOBAL_CROP_SIZE: 448
  GLOBAL_RATIO:
  - 0.75
  - 1.33
  GLOBAL_SCALE:
  - 0.4
  - 1.0
  HUE: 0.1
  INTENSITY: 0.4
  IS_AUG: true
  LOCAL_CROP_SIZE: 96
  LOCAL_RATIO:
  - 0.75
  - 1.33
  LOCAL_SCALE:
  - 0.05
  - 0.4
  NUM_GLOBAL: 2
  NUM_LOCAL: 8
  SATURATION: 0.2

LOSS:
  NAME: pera
LR_SCHEDULER:
  FINAL_VALUE: 1.0e-06
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  LEARNING_RATE: 0.001
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 20
  WARMUP_VALUE: 0
NET:
  DEPTH: 12
  DINO:
    HEAD_BOTTLENECK_DIM: 384
    HEAD_HIDDEN_DIM: 2048
    HEAD_OUT_DIM: 131072
    NUM_HEAD_LAYERS: 3
  DROP_PATH_RATE: 0.3
  DROP_RATE: 0.0
  EMBED_DIM: 768
  IN_CHANS: 3
  MLP_RATIO: 4.0
  NAME: pera
  NUM_HEADS: 12
  PATCH_SIZE: 16
  PERA:
    DINO_LOSS_WEIGHT: 1.0
    KOLEO_LOSS_WEIGHT: 0.1
    MAE_LOSS_WEIGHT: 0.01
    S_RATIO: 0.2
    T_RATIO: 0.6
NUM_EPOCHS: 200
OPTIMIZER:
  BETAS:
  - 0.9
  - 0.999
  EPS: 2.0e-05
  MOMENTUM: 0.9
  NAME: adamw
SAVE_FREQ: 10
SEED: 10
STUDENT_TEMP: 0.1
TM_SCHEDULER:
  FINAL_VALUE: 1.0
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  TEACHER_MOMENTUM: 0.992
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 0.0
TT_SCHEDULER:
  FINAL_VALUE: 0.05
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  TEACHER_TEMP: 0.05
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 30
  WARMUP_VALUE: 0.03
WD_SCHEDULER:
  FINAL_VALUE: 0.2
  FREEZE_EPOCHS: 0
  IS_RESTART: false
  T_0: 10
  T_MULT: 2
  WARMUP_EPOCHS: 0
  WARMUP_VALUE: 0.0
  WEIGHT_DECAY: 0.04